# Generated by Django 4.1 on 2022-09-14 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuarioC',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_username', models.BigAutoField(primary_key=True)),
                ('username', models.CharField(primary_key=True,unique=True ,serialize=False)),
                ('password', models.CharField(max_length=30, verbose_name='Contraseña')),
                ('perfil', models.CharField(max_length=30, verbose_name='Perfil')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=30, verbose_name='Apellido')),
                ('telefono', models.CharField(max_length=30, verbose_name='Telefono')),
                ('genero', models.EmailField(max_length=30, verbose_name='Genero')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Personal_Salud',
            fields=[
                ('id_PersonalSalud', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=30, verbose_name='Rol')),
                ('especialidad', models.CharField(max_length=60, verbose_name='Especialidad')),
                ('id_UserName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PSalud', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id_Paciente', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=30, verbose_name='Direccion')),
                ('ciudad', models.CharField(max_length=30, verbose_name='Ciudad')),
                ('fecha_nacimiento', models.DateField()),
                ('id_UserName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Paciente', to=settings.AUTH_USER_MODEL)),
                ('id_PSalud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Paciente', to='hosp_app.personal_salud')),
            ],
        ),
        migrations.CreateModel(
            name='familiar',
            fields=[
                ('id_familiar', models.AutoField(primary_key=True, serialize=False)),
                ('parentesco', models.CharField(max_length=30, verbose_name='parentesco')),
                ('correo', models.CharField(max_length=30, verbose_name='Especialidad')),
                ('id_UserName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Familiar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
