from .crearusuarioview import Crearusuarioview
from .crearpersonalview import Crearpersonalview
from .crearpacienteview import Crearpacienteview
from .crearfamiliarview import Crearfamiliarview
from .usuarioDetailsview import UsuarioDetailsview
from .crearpersonalview import Consultapersonalview
from .crearpacienteview import Consultapacienteview
from .crearfamiliarview import Consultafamiliarview
